### ISSUE TITLE
Extraneous "g" in SideIndicatorName

### ISSUE THREAD

**Issue by mpc0** [it-praktyk/Get-ADGroupDifferences#5]
Line 208 of Get-ADGroupsDifference.ps1 should "SideIndicatorName" instead of "SidegIndicatorName". Note the extra "g". 

Credit to Cclifton https://gallery.technet.microsoft.com/scriptcenter/PowerShell-function-02ac0e15/view/Discussions

**Comment by it-praktyk** [comment]
Thank you for your report.

Corrected by 0174455fe67f5cb776d6c72ec3dcc29747e916a9.
