### ISSUE TITLE
Getting syntax error

### ISSUE THREAD

**Issue by ithelpme** [it-praktyk/Get-ADGroupDifferences#6]
Syntax error at DefaultDisplayProperty.  Tried this on Windows 10 and Windows 7 powershell, both in a clean state.

![adgroup-error](https://user-images.githubusercontent.com/2293375/78944964-0c565180-7a74-11ea-9992-b6872673a326.png)

**Comment by it-praktyk** [comment]
Based on data provided I can't start troubleshooting. Sorry.
